# Generated by Django 3.2.3 on 2021-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('documents', models.FileField(upload_to='')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
